name: Build Docker base images user (Ubuntu + Alpine)

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build-ubuntu-images:
    strategy:
      matrix:
        os: [24.04]
        node: [22.x, 24.x]
#        exclude:
#          - node: 22.x
        vm: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - vm: ubuntu-latest
            os: 24.04
            node: 24.x
            arch: amd
            platform: linux/amd64
          - vm: ubuntu-latest
            os: 24.04
            node: 22.x
            arch: amd
            platform: linux/amd64
          - vm: ubuntu-24.04-arm
            os: 24.04
            arch: arm
            node: 22.x
            platform: linux/arm64,linux/arm/v7
          - vm: ubuntu-24.04-arm
            os: 24.04
            arch: arm
            node: 24.x
            platform: linux/arm64
    runs-on: ${{ matrix.vm }}
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build baseimages
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile_base_${{ matrix.os }}_user
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.node }}
          build-args: |
            NODE=${{ matrix.node }}

      - name: Modify Dockerfile_rel for testing
        run: |
          sed -i \
            "s|:latest|:${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.node }}|g" \
            ./docker/Dockerfile_rel_user

      - name: Build Signal K test docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile_rel_user
          platforms: ${{ matrix.platform }}
          build-args: |
            TAG=latest

  build-alpine-images:
    strategy:
      matrix:
        node: [22, 24]
#        exclude:
#          - node: 22
        vm: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - vm: ubuntu-latest
            node: 24
            arch: amd
            platform: linux/amd64
          - vm: ubuntu-latest
            os: 24.04
            node: 22
            arch: amd
            platform: linux/amd64
          - vm: ubuntu-24.04-arm
            arch: arm
            node: 22
            platform: linux/arm64,linux/arm/v7
          - vm: ubuntu-24.04-arm
            arch: arm
            node: 24
            platform: linux/arm64
    runs-on: ${{ matrix.vm }}
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Alpine baseimages
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile_base_alpine
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:${{ matrix.arch }}-alpine-${{ matrix.node }}
          build-args: |
            NODE=${{ matrix.node }}

  create-and-push-ubuntu-manifest:
    needs: [build-ubuntu-images]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [24.04]
        node: [22.x, 24.x]
#        exclude:
#          - node: 22.x

    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create and push multi-arch manifest to GHCR and Docker Hub
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:latest-${{ matrix.os }}-${{ matrix.node }}
#            kgustafs/signalk-server-base:latest-${{ matrix.os }}-${{ matrix.node }}
          sources: |
            ghcr.io/kegustafsson/signalk-server-base:amd-${{ matrix.os }}-${{ matrix.node }}
            ghcr.io/kegustafsson/signalk-server-base:arm-${{ matrix.os }}-${{ matrix.node }}

  create-and-push-alpine-manifest:
    needs: [build-alpine-images]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22, 24]
#        exclude:
#          - node: 22
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create and push multi-arch manifest to GHCR and Docker Hub
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:latest-alpine-${{ matrix.node }}
#            kgustafs/signalk-server-base:latest-alpine-${{ matrix.node }}
          sources: |
            ghcr.io/kegustafsson/signalk-server-base:amd-alpine-${{ matrix.node }}
            ghcr.io/kegustafsson/signalk-server-base:arm-alpine-${{ matrix.node }}

  housekeeping:
    needs: [create-and-push-ubuntu-manifest, create-and-push-alpine-manifest]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Remove Docker Image from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: signalk-server-base
          delete-untagged: true
          delete-tags: amd-*,arm-*
          token: ${{ secrets.GHCR_TOKEN_NEW }}

  slack:
    runs-on: ubuntu-latest
    needs: [housekeeping]
    steps:
      - name: Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Ubuntu 24.04 + Alpine base images ready"}' https://hooks.slack.com/services/${{ secrets.SLACK }}
